apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-predictor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: salary-predictor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
